Feat/add icon show password
Pews-DEV/book-writer-frontend pull request #16
Opened 2022-04-19 22:10 UTC by gabrielduete

## Infos
#### O que está sendo entregue?
Botão para mostrar a senha enquanto digita.

#### O que impacta?
Todos os inputs dos modals.

#### Plano de rollback
Revert do Merge

#### Onde monitorar
Via Local

#### Evidências
![image](https://user-images.githubusercontent.com/59345698/164110034-ebd12518-a92c-485d-b025-4956b5d6d7d9.png)

![image](https://user-images.githubusercontent.com/59345698/164110019-caa5206b-aa2f-4e01-b363-bed42168cd62.png)

2022-04-21 17:35 UTC, oopaze requested changes

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.jsx
> +import CloseEye from '@/assets/img/close-eye(TEMPORARY).png'
Sugestão: Acho que é uma boa pular uma linha pra diferenciar os níveis dos imports. Mais ou menos assim:
```suggestion
import { useState } from 'react'

import * as S from './styles'

import Eye from '@/assets/img/eye.png'
import CloseEye from '@/assets/img/close-eye(TEMPORARY).png'
```

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.jsx
> +  const validatePassword = typeInput === 'password'
Sugestão: A gente poderia reescrever essa variável como `InputType`, que ficaria tipo do input quando traduzido.

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.jsx
> +          data-testid={'button-validated'}
Será que esse teste id não ficaria mais auto explicativo se fosse algo como `toggleInputTypeButton`  / `showPasswordButton`, algo assim.

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.test.js
> +describe('Input component tests', () => {
Acho que é importante testar se o click do botão muda o tipo do input. 

```javascript
it.todo('checks if click in toggleInputTypeButton will set input type to text')
it.todo('checks if click in toggleInputTypeButton twice will set input type to text and then password')
```

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/styles.js
> +  width: var(--spacing-5);
Acho que a gente pode padronizar o uso dos spacings somente pra spacings properties mesmo: 
- `padding`
- `margin`
- `gap`
- `letter-spacing`
- `word-spacing`
- e etc...

O objetivo dessas padronizações é se a gente precisar mudar esses valores mais tarde, a gente muda somente a variável.

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.jsx
> +import CloseEye from '@/assets/img/close-eye(TEMPORARY).png'
O que acha da gente só manter o nome desse arquivo somente como `close-eye`? Se caso a gente mudar mais tarde, a sobrescreve o arquivo e aí o git mostra direitinho essa mudança, igual aquele print que cê me mandou lembra?

2022-04-21 17:35 UTC, oopaze commented on src/components/Modals/LoginModal/index.jsx
>  import RegisterModal from '../RegisterModal'
Talvez seja uma boa aproveitar que tu já fez uma alteração nesse arquivo e organizar os imports direitin. 😄 

Só se quiser mesmo.

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/index.jsx
> +const Input = (props) => {
Tô subindo um PR adicionando os prop types dos componentes já existentes. Será que não seria uma boa mandar esse component já com os proptypes certinhos?

2022-04-21 17:35 UTC, oopaze commented on src/components/Inputs/styles.js
> +  right: var(--spacing-4);
https://github.com/Pews-DEV/book-writer-frontend/pull/16#discussion_r855422303

2022-04-22 17:49 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +import CloseEye from '@/assets/img/close-eye(TEMPORARY).png'
Nice, feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/57ab5bd50a2d57d6ba8465e9036af689ad6b7cb8

2022-04-22 17:49 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +  const validatePassword = typeInput === 'password'
Boa! Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/f91401b9c1826bdbcf04029d6b6b16bc4d9a026b

2022-04-22 17:50 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +          data-testid={'button-validated'}
Boa, formatei igual os outros testes pra seguir o padrão. 
Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/4b966fba78367638b6942f1bbacaec1c22afc9b6

2022-04-22 17:51 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +const Input = (props) => {
Feshow! Assim que se subir eu arrumo aqui!

2022-04-22 17:57 UTC, gabrielduete commented on src/components/Inputs/styles.js
> +  width: var(--spacing-5);
Acho que pode ser melhor mesmo. Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/f87b8e7464df79b97c1744391c5fdf282359ee71

2022-04-22 18:21 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +import CloseEye from '@/assets/img/close-eye(TEMPORARY).png'
Hehe boa! Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/ba3020d010416dba5257b801ee1eef7af32598b4

2022-04-22 18:22 UTC, gabrielduete commented on src/components/Modals/LoginModal/index.jsx
>  import RegisterModal from '../RegisterModal'
Hehe, boa! Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/300620d028783ce06d1c53b9317729acdfcdde46

2022-04-22 18:32 UTC, oopaze commented on src/components/Inputs/index.jsx
> +const Input = (props) => {
Já subi o meu, mas como o `Proptypes` vem com `React`, tu pode implementar aí sem necessitar depender do meu PR.

2022-04-22 23:03 UTC, gabrielduete commented on src/components/Inputs/index.jsx
> +const Input = (props) => {
Boa! Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/d3f9ea1490178c6e1538b5c90fdc5e9cd5650bb8

2022-04-22 23:03 UTC, gabrielduete commented on src/components/Inputs/index.test.js
> +describe('Input component tests', () => {
Muito bom! Feito em https://github.com/Pews-DEV/book-writer-frontend/pull/16/commits/fe10ad90db08077bb443877beb37987630bea65d

2022-04-24 22:40 UTC, Pews-DEV commented on src/components/Inputs/styles.js
> +`
Sugestão: dar um espaçamento no final do arquivo, assim como Zé dos reviews fala aqui: https://github.com/Pews-DEV/book-writer-frontend/pull/5#discussion_r838604435

2022-04-25 21:15 UTC, gabrielduete commented on src/components/Inputs/styles.js
> +`
Opa, Pedro! Mano, pior que já tá com a linha em branco certinha, n sei pq não ta aparecendo aqui

2022-04-25 21:57 UTC, oopaze approved these changes

2022-04-25 21:58 UTC, oopaze commented
🚀

2022-04-25 21:58 UTC, Pews-DEV approved these changes
Dale!

2022-04-25 22:00 UTC, merged